### ISSUE TITLE
Make a TiDB adapter

### ISSUE THREAD

**Issue by hsluoyz** [casbin/tidb-adapter#1]
TiDB is a very popular distributed DB: https://github.com/pingcap/tidb , also written in Golang.

We need to make an adapter specifically for TiDB.

**Comment by hsluoyz** [comment]
@closetool

**Comment by tangyang9464** [comment]
@hsluoyz  TiDB is compatible with MySQL,so we can use gorm to connect to TiDB like MySQL.Can I just make pr to gorm-adapter to add TiDB support?This repository is not necessary

**Comment by hsluoyz** [comment]
@tangyang9464 we should explicitly make a TiDB adapter using TiDB Go SDK.

**Comment by hsluoyz** [comment]
@tangyang9464 you are right. Let's suspend this issue now. Please work on this one: https://github.com/casbin/tikv-watcher

**Comment by hsluoyz** [comment]
Replaced by: https://github.com/casbin/tikv-watcher/issues/1
